services:
  frontend:
    image: vue-morse
    build: vue-project/Dockerfile
    ports:
    - "5173:5173"

  backend:
    image: backend-morse
    build: backend/Dockerfile
    ports:
    - "8080:8080"
